### ISSUE TITLE
Remove old plugin name fallbacks

### ISSUE THREAD

**Issue by martinheidegger** [OwnYourData/oyd-pia2#14]
Looking up plugins seems to have some old logic in there. That can be removed, right?

https://github.com/OwnYourData/oyd-pia2/blob/c5fb5f544c75241e4e1605ae7f3e782aa4b35f10/app/controllers/api/v1/plugins_controller.rb#L115-L125

**Comment by fabianekc** [comment]
fixed in https://github.com/OwnYourData/oyd-pia2/commit/53ab7ee2e17b58403ba16a8033802cec74c8ef0a
